#!/bin/bash

# somehow tensorflow cannot find the right cuda & cudnn lib to load at runtime,
# so set some env vars to correct it
export PATH=/usr/local/cuda-11.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/include:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2/extras/CUPTI/lib64

dataset_dir="/data/work/dataset/mvtec"

python3 train.py -d $dataset_dir/toothbrush -a baselineCAE -b 32 -l ssim -c grayscale --inspect
python3 train.py -d $dataset_dir/capsule -a mvtecCAE -b 32 -l ssim -c grayscale --inspect
#python3 train.py -d $dataset_dir/hazelnut -a resnetCAE -b 32 -l mssim -c rgb --inspect
#python3 train.py -d $dataset_dir/pill -a inceptionCAE -b 32 -l mssim -c rgb --inspect
